apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opensoha
resources:
  - deployment.yaml
configMapGenerator:
  - name: soha-remote-dev-scripts
    files:
      - source-sync.sh
      - backend.sh
      - web.sh
