apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecrux.fullname" . }}
  labels:
    {{- include "kubecrux.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: app
    {{- include "kubecrux.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
