apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubecrux.postgresServiceName" . }}-data
  labels:
    {{- include "kubecrux.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubecrux.postgresServiceName" . }}
  labels:
    {{- include "kubecrux.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      {{- include "kubecrux.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        {{- include "kubecrux.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubecrux.fullname" . }}-config
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "kubecrux.postgresServiceName" . }}-data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubecrux.postgresServiceName" . }}
  labels:
    {{- include "kubecrux.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: postgres
    {{- include "kubecrux.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
