services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: kubecrux
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: pgsql
    ports:
      - "5432:5432"
    volumes:
      - kubecrux-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgsql -d kubecrux"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  kubecrux-postgres-data:
