apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubecrux.fullname" . }}
  labels:
    {{- include "kubecrux.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      {{- include "kubecrux.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        {{- include "kubecrux.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kubecrux
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KC_CONFIG_FILE
              value: /app/configs/config.yaml
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: app-config
              mountPath: /app/configs/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: app-config
          secret:
            secretName: {{ include "kubecrux.fullname" . }}-config
