ALTER TABLE menus
    ALTER COLUMN section DROP NOT NULL;

UPDATE menus
SET section = NULL,
    updated_at = NOW()
WHERE section = 'platform'
  AND id IN (
    'dashboard',
    'cluster-resources-nodes',
    'extensions',
    'helm',
    'helm-releases',
    'helm-charts',
    'platform-access-control',
    'platform-access-control-serviceaccounts',
    'platform-access-control-clusterroles',
    'platform-access-control-roles',
    'platform-access-control-clusterrolebindings',
    'platform-access-control-rolebindings',
    'workloads',
    'workloads-overview',
    'workloads-deployments',
    'workloads-pods',
    'workloads-statefulsets',
    'workloads-daemonsets',
    'workloads-jobs',
    'workloads-cronjobs',
    'workloads-replicasets',
    'workloads-replicationcontrollers',
    'configuration',
    'configuration-configmaps',
    'configuration-secrets',
    'configuration-resourcequotas',
    'configuration-limitranges',
    'configuration-hpas',
    'configuration-poddisruptionbudgets',
    'configuration-priorityclasses',
    'configuration-runtimeclasses',
    'configuration-leases',
    'configuration-mutatingwebhookconfigurations',
    'configuration-validatingwebhookconfigurations',
    'network',
    'network-topology',
    'network-services',
    'network-ingresses',
    'network-gateways',
    'network-endpointslices',
    'network-ingressclasses',
    'network-networkpolicies',
    'network-port-forward',
    'storage',
    'storage-pvc',
    'storage-pv',
    'storage-classes',
    'clusters'
  );
