apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opensoha
resources:
  - ../remote-dev
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: soha-dev
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: soha-dev
      spec:
        template:
          spec:
            containers:
              - name: source-sync
                env:
                  - name: SYNC_MODE
                    value: local
