apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soha
resources:
  - deployment.yaml
images:
  - name: pgvector/pgvector
    newTag: 0.8.5-pg18-trixie
  - name: yshanchui/soha
    newTag: latest
