package routes

import (
	"github.com/gin-gonic/gin"
	cfgpkg "github.com/opensoha/soha/internal/infrastructure/config"
)

func registerDeliveryRoutes(protected gin.IRoutes, cfg cfgpkg.Config, deps Dependencies) {
	if !cfg.Modules.Delivery.Enabled {
		return
	}

	protected.GET("/application-environments", deps.Catalog.ListApplicationEnvironments)
	protected.GET("/application-environments/:applicationEnvironmentID", deps.Catalog.GetApplicationEnvironment)
	protected.GET("/application-environments/:applicationEnvironmentID/detail", deps.Delivery.GetApplicationEnvironmentDetail)
	protected.GET("/application-environments/target-candidates", deps.Delivery.ListTargetCandidates)
	protected.GET("/delivery/release-bundles", deps.Delivery.ListReleaseBundles)
	protected.GET("/delivery/release-bundles/:bundleID", deps.Delivery.GetReleaseBundle)
	protected.GET("/delivery/release-bundles/:bundleID/artifacts", deps.Delivery.ListReleaseBundleArtifacts)
	protected.GET("/delivery/execution-tasks", deps.Delivery.ListExecutionTasks)
	protected.GET("/delivery/execution-tasks/:taskID", deps.Delivery.GetExecutionTask)
	protected.GET("/delivery/execution-tasks/:taskID/logs", deps.Delivery.ListExecutionLogs)
	protected.GET("/delivery/execution-tasks/:taskID/artifacts", deps.Delivery.ListExecutionArtifacts)
	protected.POST("/delivery/execution-tasks/:taskID/cancel", deps.Delivery.CancelExecutionTask)
	protected.POST("/delivery/execution-tasks/:taskID/retry", deps.Delivery.RetryExecutionTask)
	protected.GET("/delivery/blueprints", deps.Delivery.ListDeliveryBlueprints)
	protected.POST("/delivery/blueprints", deps.Delivery.CreateDeliveryBlueprint)
	protected.PUT("/delivery/blueprints/:blueprintID", deps.Delivery.UpdateDeliveryBlueprint)
	protected.POST("/delivery/blueprints/:blueprintID/render-spec", deps.Delivery.RenderDeliveryBlueprintSpec)
	protected.POST("/delivery/blueprints/:blueprintID/bootstrap-application", deps.Delivery.BootstrapApplicationFromBlueprint)
	protected.POST("/application-environments", deps.Catalog.CreateApplicationEnvironment)
	protected.PUT("/application-environments/:applicationEnvironmentID", deps.Catalog.UpdateApplicationEnvironment)
	protected.DELETE("/application-environments/:applicationEnvironmentID", deps.Catalog.DeleteApplicationEnvironment)
	protected.GET("/build-templates", deps.Catalog.ListBuildTemplates)
	protected.POST("/build-templates", deps.Catalog.CreateBuildTemplate)
	protected.PUT("/build-templates/:buildTemplateID", deps.Catalog.UpdateBuildTemplate)
	protected.DELETE("/build-templates/:buildTemplateID", deps.Catalog.DeleteBuildTemplate)
	protected.GET("/workflow-templates", deps.Catalog.ListWorkflowTemplates)
	protected.POST("/workflow-templates", deps.Catalog.CreateWorkflowTemplate)
	protected.PUT("/workflow-templates/:workflowTemplateID", deps.Catalog.UpdateWorkflowTemplate)
	protected.DELETE("/workflow-templates/:workflowTemplateID", deps.Catalog.DeleteWorkflowTemplate)
	protected.GET("/applications", deps.Applications.ListApplications)
	protected.POST("/applications", deps.Applications.CreateApplication)
	protected.GET("/applications/:applicationID", deps.Applications.GetApplication)
	protected.GET("/applications/:applicationID/detail", deps.Delivery.GetApplicationDetail)
	protected.GET("/applications/:applicationID/runtime", deps.Delivery.GetApplicationRuntimeDetail)
	protected.POST("/applications/:applicationID/delivery-actions", deps.Delivery.TriggerApplicationDeliveryAction)
	protected.GET("/applications/:applicationID/application-environments/:applicationEnvironmentID/workloads/:workloadName/runtime", deps.Delivery.GetApplicationWorkloadRuntimeDetail)
	protected.GET("/applications/:applicationID/services", deps.Applications.ListApplicationServices)
	protected.POST("/applications/:applicationID/services", deps.Applications.CreateApplicationService)
	protected.GET("/applications/:applicationID/services/:serviceID", deps.Applications.GetApplicationService)
	protected.PUT("/applications/:applicationID/services/:serviceID", deps.Applications.UpdateApplicationService)
	protected.DELETE("/applications/:applicationID/services/:serviceID", deps.Applications.DeleteApplicationService)
	protected.PUT("/applications/:applicationID", deps.Applications.UpdateApplication)
	protected.DELETE("/applications/:applicationID", deps.Applications.DeleteApplication)
	protected.GET("/builds", deps.Builds.ListBuilds)
	protected.POST("/builds/trigger", deps.Builds.TriggerBuild)
	protected.GET("/workflows", deps.Workflows.List)
	protected.POST("/workflows/trigger", deps.Workflows.Trigger)
	protected.POST("/workflows/:workflowRunID/approve", deps.Workflows.Approve)
	protected.POST("/workflows/:workflowRunID/reject", deps.Workflows.Reject)
	protected.GET("/registries", deps.Registries.List)
	protected.POST("/registries", deps.Registries.Create)
	protected.PUT("/registries/:connectionID", deps.Registries.Update)
	protected.DELETE("/registries/:connectionID", deps.Registries.Delete)
	protected.GET("/releases", deps.Releases.ListReleases)
	protected.POST("/releases/trigger", deps.Releases.TriggerRelease)
	protected.GET("/delivery/release-board", deps.Delivery.ListReleaseBoard)
	protected.GET("/integrations/gitlab/projects", deps.Applications.ListGitRepositories)
	protected.GET("/integrations/gitlab/branches", deps.Applications.ListGitBranches)
	protected.GET("/integrations/gitlab/tags", deps.Applications.ListGitTags)
}
