package routes

import "github.com/gin-gonic/gin"

func registerPlatformRoutes(protected gin.IRoutes, deps Dependencies) {
	registerPlatformClusterRoutes(protected, deps)
	registerPlatformWorkloadRoutes(protected, deps)
	registerPlatformConfigurationRoutes(protected, deps)
	registerPlatformNetworkStorageRoutes(protected, deps)
	registerPlatformExtensionRoutes(protected, deps)
}

func registerPlatformClusterRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/clusters", deps.Platform.ListClusters)
	protected.GET("/clusters/capabilities", deps.Platform.ClusterCapabilityMatrix)
	protected.POST("/clusters", deps.Platform.CreateCluster)
	protected.PUT("/clusters/:clusterID", deps.Platform.UpdateCluster)
	protected.DELETE("/clusters/:clusterID", deps.Platform.DeleteCluster)
	protected.GET("/clusters/:clusterID/detail", deps.Platform.DescribeCluster)
	protected.GET("/clusters/:clusterID/namespaces", deps.Platform.ListNamespaces)
	protected.POST("/clusters/:clusterID/namespaces", deps.Platform.CreateNamespace)
	protected.PUT("/clusters/:clusterID/namespaces/:namespaceName", deps.Platform.UpdateNamespace)
	protected.DELETE("/clusters/:clusterID/namespaces/:namespaceName", deps.Platform.DeleteNamespace)

	protected.GET("/clusters/:clusterID/infrastructure/nodes", deps.Platform.ListNodes)
	protected.GET("/clusters/:clusterID/infrastructure/nodes/:nodeName/detail", deps.Platform.GetNodeDetail)
	protected.GET("/clusters/:clusterID/infrastructure/nodes/:nodeName/yaml", deps.Platform.GetNodeYAML)
	protected.PUT("/clusters/:clusterID/infrastructure/nodes/:nodeName/yaml", deps.Platform.ApplyNodeYAML)
	protected.PUT("/clusters/:clusterID/infrastructure/nodes/:nodeName", deps.Platform.UpdateNode)
	protected.DELETE("/clusters/:clusterID/infrastructure/nodes/:nodeName", deps.Platform.DeleteNode)

}

func registerPlatformWorkloadRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/clusters/:clusterID/workloads/overview", deps.Platform.GetWorkloadOverview)
	protected.GET("/clusters/:clusterID/workloads/pods", deps.Platform.ListPods)
	protected.GET("/clusters/:clusterID/workloads/pods/:podName/detail", deps.Platform.GetPodDetail)
	protected.DELETE("/clusters/:clusterID/workloads/pods/:podName", deps.Platform.DeletePod)
	protected.GET("/clusters/:clusterID/workloads/pods/:podName/logs", deps.Platform.GetPodLogs)
	protected.GET("/clusters/:clusterID/workloads/pods/:podName/logs/stream", deps.Platform.StreamPodLogs)
	protected.GET("/clusters/:clusterID/workloads/pods/:podName/yaml", deps.Platform.GetPodYAML)
	protected.PUT("/clusters/:clusterID/workloads/pods/:podName/yaml", deps.Platform.ApplyPodYAML)
	protected.GET("/clusters/:clusterID/workloads/pods/:podName/metrics", deps.Platform.GetPodMetrics)
	protected.POST("/clusters/:clusterID/workloads/pods/:podName/exec", deps.Platform.ExecPod)
	protected.GET("/clusters/:clusterID/workloads/pods/:podName/terminal", deps.Platform.StreamPodTerminal)
	protected.GET("/clusters/:clusterID/workloads/deployments", deps.Platform.ListDeployments)
	protected.GET("/clusters/:clusterID/workloads/deployments/:deploymentName/detail", deps.Platform.GetDeploymentDetail)
	protected.GET("/clusters/:clusterID/workloads/deployments/:deploymentName/yaml", deps.Platform.GetDeploymentYAML)
	protected.PUT("/clusters/:clusterID/workloads/deployments/:deploymentName/yaml", deps.Platform.ApplyDeploymentYAML)
	protected.GET("/clusters/:clusterID/workloads/deployments/:deploymentName/metrics", deps.Platform.GetDeploymentMetrics)
	protected.GET("/clusters/:clusterID/workloads/deployments/:deploymentName/rollout-status", deps.Platform.GetDeploymentRolloutStatus)
	protected.GET("/clusters/:clusterID/workloads/deployments/:deploymentName/rollouts", deps.Platform.ListDeploymentRollouts)
	protected.GET("/clusters/:clusterID/workloads/statefulsets", deps.Platform.ListStatefulSets)
	protected.GET("/clusters/:clusterID/workloads/statefulsets/:statefulSetName/detail", deps.Platform.GetStatefulSetDetail)
	protected.GET("/clusters/:clusterID/workloads/statefulsets/:statefulSetName/yaml", deps.Platform.GetStatefulSetYAML)
	protected.PUT("/clusters/:clusterID/workloads/statefulsets/:statefulSetName/yaml", deps.Platform.ApplyStatefulSetYAML)
	protected.GET("/clusters/:clusterID/workloads/statefulsets/:statefulSetName/metrics", deps.Platform.GetStatefulSetMetrics)
	protected.GET("/clusters/:clusterID/workloads/daemonsets", deps.Platform.ListDaemonSets)
	protected.GET("/clusters/:clusterID/workloads/daemonsets/:daemonSetName/detail", deps.Platform.GetDaemonSetDetail)
	protected.GET("/clusters/:clusterID/workloads/daemonsets/:daemonSetName/yaml", deps.Platform.GetDaemonSetYAML)
	protected.PUT("/clusters/:clusterID/workloads/daemonsets/:daemonSetName/yaml", deps.Platform.ApplyDaemonSetYAML)
	protected.GET("/clusters/:clusterID/workloads/daemonsets/:daemonSetName/metrics", deps.Platform.GetDaemonSetMetrics)
	protected.GET("/clusters/:clusterID/workloads/jobs", deps.Platform.ListJobs)
	protected.GET("/clusters/:clusterID/workloads/jobs/:jobName/detail", deps.Platform.GetJobDetail)
	protected.GET("/clusters/:clusterID/workloads/jobs/:jobName/yaml", deps.Platform.GetJobYAML)
	protected.PUT("/clusters/:clusterID/workloads/jobs/:jobName/yaml", deps.Platform.ApplyJobYAML)
	protected.GET("/clusters/:clusterID/workloads/cronjobs", deps.Platform.ListCronJobs)
	protected.GET("/clusters/:clusterID/workloads/replicasets", deps.Platform.ListReplicaSets)
	protected.GET("/clusters/:clusterID/workloads/replicasets/:replicaSetName/yaml", deps.Platform.GetReplicaSetYAML)
	protected.PUT("/clusters/:clusterID/workloads/replicasets/:replicaSetName/yaml", deps.Platform.ApplyReplicaSetYAML)
	protected.GET("/clusters/:clusterID/workloads/cronjobs/:cronJobName/detail", deps.Platform.GetCronJobDetail)
	protected.GET("/clusters/:clusterID/workloads/cronjobs/:cronJobName/yaml", deps.Platform.GetCronJobYAML)
	protected.PUT("/clusters/:clusterID/workloads/cronjobs/:cronJobName/yaml", deps.Platform.ApplyCronJobYAML)
	protected.POST("/clusters/:clusterID/workloads/cronjobs/:cronJobName/suspend", deps.Platform.SetCronJobSuspend)
	protected.GET("/clusters/:clusterID/workloads/replicationcontrollers", deps.Platform.ListReplicationControllers)
	protected.POST("/clusters/:clusterID/workloads/deployments/restart", deps.Platform.RestartDeployment)
	protected.POST("/clusters/:clusterID/workloads/deployments/rollback", deps.Platform.RollbackDeployment)
	protected.POST("/clusters/:clusterID/workloads/deployments/scale", deps.Platform.ScaleDeployment)
	protected.POST("/clusters/:clusterID/workloads/statefulsets/restart", deps.Platform.RestartStatefulSet)
	protected.POST("/clusters/:clusterID/workloads/statefulsets/scale", deps.Platform.ScaleStatefulSet)
	protected.POST("/clusters/:clusterID/workloads/daemonsets/restart", deps.Platform.RestartDaemonSet)

}

func registerPlatformConfigurationRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/clusters/:clusterID/configuration/configmaps", deps.Platform.ListConfigMaps)
	protected.POST("/clusters/:clusterID/configuration/configmaps", deps.Platform.CreateConfigMap)
	protected.GET("/clusters/:clusterID/configuration/configmaps/:name/detail", deps.Platform.GetConfigMapDetail)
	protected.PUT("/clusters/:clusterID/configuration/configmaps/:name/data", deps.Platform.UpdateConfigMapData)
	protected.GET("/clusters/:clusterID/configuration/configmaps/:name/references", deps.Platform.ListConfigMapReferences)
	protected.GET("/clusters/:clusterID/configuration/secrets", deps.Platform.ListSecrets)
	protected.POST("/clusters/:clusterID/configuration/secrets", deps.Platform.CreateSecret)
	protected.GET("/clusters/:clusterID/configuration/secrets/:name/detail", deps.Platform.GetSecretDetail)
	protected.PUT("/clusters/:clusterID/configuration/secrets/:name/data", deps.Platform.UpdateSecretData)
	protected.GET("/clusters/:clusterID/configuration/secrets/:name/references", deps.Platform.ListSecretReferences)
	protected.GET("/clusters/:clusterID/configuration/hpas", deps.Platform.ListHorizontalPodAutoscalers)
	protected.GET("/clusters/:clusterID/configuration/poddisruptionbudgets", deps.Platform.ListPodDisruptionBudgets)
	protected.GET("/clusters/:clusterID/configuration/priorityclasses", deps.Platform.ListPriorityClasses)
	protected.GET("/clusters/:clusterID/configuration/runtimeclasses", deps.Platform.ListRuntimeClasses)
	protected.GET("/clusters/:clusterID/configuration/mutatingwebhookconfigurations", deps.Platform.ListMutatingWebhookConfigurations)
	protected.GET("/clusters/:clusterID/configuration/validatingwebhookconfigurations", deps.Platform.ListValidatingWebhookConfigurations)
	protected.GET("/clusters/:clusterID/configuration/resourcequotas", deps.Platform.ListResourceQuotas)
	protected.GET("/clusters/:clusterID/configuration/limitranges", deps.Platform.ListLimitRanges)
	protected.GET("/clusters/:clusterID/configuration/leases", deps.Platform.ListLeases)

	protected.GET("/clusters/:clusterID/access-control/serviceaccounts", deps.Platform.ListServiceAccounts)
	protected.POST("/clusters/:clusterID/access-control/serviceaccounts", deps.Platform.CreateServiceAccount)
	protected.GET("/clusters/:clusterID/access-control/serviceaccounts/:name/detail", deps.Platform.GetServiceAccountDetail)
	protected.GET("/clusters/:clusterID/access-control/roles", deps.Platform.ListRoles)
	protected.POST("/clusters/:clusterID/access-control/roles", deps.Platform.CreateRole)
	protected.GET("/clusters/:clusterID/access-control/roles/:name/detail", deps.Platform.GetRoleDetail)
	protected.GET("/clusters/:clusterID/access-control/rolebindings", deps.Platform.ListRoleBindings)
	protected.POST("/clusters/:clusterID/access-control/rolebindings", deps.Platform.CreateRoleBinding)
	protected.GET("/clusters/:clusterID/access-control/rolebindings/:name/detail", deps.Platform.GetRoleBindingDetail)
	protected.GET("/clusters/:clusterID/access-control/clusterroles", deps.Platform.ListClusterRoles)
	protected.POST("/clusters/:clusterID/access-control/clusterroles", deps.Platform.CreateClusterRole)
	protected.GET("/clusters/:clusterID/access-control/clusterroles/:name/detail", deps.Platform.GetClusterRoleDetail)
	protected.GET("/clusters/:clusterID/access-control/clusterrolebindings", deps.Platform.ListClusterRoleBindings)
	protected.POST("/clusters/:clusterID/access-control/clusterrolebindings", deps.Platform.CreateClusterRoleBinding)
	protected.GET("/clusters/:clusterID/access-control/clusterrolebindings/:name/detail", deps.Platform.GetClusterRoleBindingDetail)

}

func registerPlatformNetworkStorageRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/clusters/:clusterID/network/services", deps.Platform.ListServices)
	protected.GET("/clusters/:clusterID/network/topology", deps.Platform.GetNetworkTopology)
	protected.GET("/clusters/:clusterID/network/services/:serviceName/metrics", deps.Platform.GetServiceMetrics)
	protected.GET("/clusters/:clusterID/network/ingresses", deps.Platform.ListIngresses)
	protected.GET("/clusters/:clusterID/network/endpointslices", deps.Platform.ListEndpointSlices)
	protected.GET("/clusters/:clusterID/network/networkpolicies", deps.Platform.ListNetworkPolicies)
	protected.GET("/clusters/:clusterID/network/gatewayclasses", deps.Platform.ListGatewayClasses)
	protected.GET("/clusters/:clusterID/network/gateways", deps.Platform.ListGateways)
	protected.GET("/clusters/:clusterID/network/httproutes", deps.Platform.ListHTTPRoutes)
	protected.GET("/clusters/:clusterID/network/backendtlspolicies", deps.Platform.ListBackendTLSPolicies)
	protected.GET("/clusters/:clusterID/network/grpcroutes", deps.Platform.ListGRPCRoutes)
	protected.GET("/clusters/:clusterID/network/referencegrants", deps.Platform.ListReferenceGrants)
	protected.GET("/clusters/:clusterID/network/ingressclasses", deps.Platform.ListIngressClasses)
	protected.GET("/clusters/:clusterID/network/port-forwards", deps.Platform.ListPortForwards)
	protected.POST("/clusters/:clusterID/network/port-forwards", deps.Platform.RegisterPortForward)
	protected.DELETE("/clusters/:clusterID/network/port-forwards/:sessionID", deps.Platform.StopPortForward)

	protected.GET("/clusters/:clusterID/storage/persistentvolumeclaims", deps.Platform.ListPersistentVolumeClaims)
	protected.POST("/clusters/:clusterID/storage/persistentvolumeclaims", deps.Platform.CreatePersistentVolumeClaim)
	protected.GET("/clusters/:clusterID/storage/persistentvolumeclaims/:name/detail", deps.Platform.GetPersistentVolumeClaimDetail)
	protected.GET("/clusters/:clusterID/storage/persistentvolumes", deps.Platform.ListPersistentVolumes)
	protected.POST("/clusters/:clusterID/storage/persistentvolumes", deps.Platform.CreatePersistentVolume)
	protected.GET("/clusters/:clusterID/storage/persistentvolumes/:name/detail", deps.Platform.GetPersistentVolumeDetail)
	protected.GET("/clusters/:clusterID/storage/storageclasses", deps.Platform.ListStorageClasses)
	protected.POST("/clusters/:clusterID/storage/storageclasses", deps.Platform.CreateStorageClass)
	protected.GET("/clusters/:clusterID/storage/storageclasses/:name/detail", deps.Platform.GetStorageClassDetail)

	deps.Platform.RegisterGenericResourceRoutes(protected)
	deps.Platform.RegisterWorkloadDeleteRoutes(protected)
}

func registerPlatformExtensionRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/clusters/:clusterID/extensions/crds", deps.Platform.ListCRDs)
	protected.GET("/clusters/:clusterID/extensions/crds/:crdName/resources", deps.Platform.ListCRDResources)
	protected.POST("/clusters/:clusterID/extensions/crds/:crdName/resources", deps.Platform.CreateCRDResource)
	protected.GET("/clusters/:clusterID/extensions/crds/:crdName/resources/:name/yaml", deps.Platform.GetCRDResourceYAML)
	protected.PUT("/clusters/:clusterID/extensions/crds/:crdName/resources/:name/yaml", deps.Platform.ApplyCRDResourceYAML)
	protected.DELETE("/clusters/:clusterID/extensions/crds/:crdName/resources/:name", deps.Platform.DeleteCRDResource)

	protected.GET("/clusters/:clusterID/helm/charts", deps.Platform.ListHelmCharts)
	protected.GET("/clusters/:clusterID/helm/charts/values", deps.Platform.GetHelmChartValuesTemplate)
	protected.POST("/clusters/:clusterID/helm/charts/install", deps.Platform.InstallHelmChart)
	protected.GET("/clusters/:clusterID/helm/charts/:repositoryName/:chartName", deps.Platform.GetHelmChartDetail)
	protected.GET("/clusters/:clusterID/helm/releases", deps.Platform.ListHelmReleases)
	protected.GET("/clusters/:clusterID/helm/releases/:releaseName/detail", deps.Platform.GetHelmReleaseDetail)
	protected.GET("/clusters/:clusterID/helm/releases/:releaseName/history", deps.Platform.ListHelmReleaseHistory)
	protected.GET("/clusters/:clusterID/helm/releases/:releaseName/values", deps.Platform.GetHelmReleaseValues)
	protected.PUT("/clusters/:clusterID/helm/releases/:releaseName/values", deps.Platform.UpdateHelmReleaseValues)
	protected.DELETE("/clusters/:clusterID/helm/releases/:releaseName", deps.Platform.DeleteHelmRelease)

	protected.GET("/clusters/:clusterID/events", deps.Platform.ListClusterEvents)
}
