package routes

import (
	"github.com/gin-gonic/gin"
	cfgpkg "github.com/opensoha/soha/internal/infrastructure/config"
)

func registerDeliveryRoutes(protected gin.IRoutes, cfg cfgpkg.Config, deps Dependencies) {
	_ = cfg
	registerDeliveryRuntimeRoutes(protected, deps)
	registerDeliveryCatalogRoutes(protected, deps)
	registerDeliveryApplicationRoutes(protected, deps)
	registerDeliveryExecutionRoutes(protected, deps)
}

func registerDeliveryRuntimeRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/application-environments", deps.Catalog.ListApplicationEnvironments)
	protected.GET("/application-environments/:applicationEnvironmentID", deps.Catalog.GetApplicationEnvironment)
	protected.GET("/application-environments/:applicationEnvironmentID/detail", deps.Delivery.GetApplicationEnvironmentDetail)
	protected.GET("/application-environments/target-candidates", deps.Delivery.ListTargetCandidates)
	protected.GET("/delivery/artifacts", deps.Delivery.ListArtifacts)
	protected.GET("/delivery/runtime/builds/:buildID", deps.Delivery.GetBuildRuntimeDetail)
	protected.GET("/delivery/runtime/workflows/:workflowRunID", deps.Delivery.GetWorkflowRuntimeDetail)
	protected.GET("/delivery/runtime/releases/:releaseID", deps.Delivery.GetReleaseRuntimeDetail)
	protected.GET("/delivery/runtime/release-bundles/:bundleID", deps.Delivery.GetReleaseBundleRuntimeDetail)
	protected.GET("/delivery/runtime/execution-tasks/:taskID", deps.Delivery.GetExecutionTaskRuntimeDetail)
	protected.GET("/delivery/release-bundles", deps.Delivery.ListReleaseBundles)
	protected.GET("/delivery/release-bundles/:bundleID", deps.Delivery.GetReleaseBundle)
	protected.GET("/delivery/release-bundles/:bundleID/artifacts", deps.Delivery.ListReleaseBundleArtifacts)
	protected.GET("/delivery/execution-tasks", deps.Delivery.ListExecutionTasks)
	protected.GET("/delivery/execution-tasks/:taskID", deps.Delivery.GetExecutionTask)
	protected.GET("/delivery/execution-tasks/:taskID/logs", deps.Delivery.ListExecutionLogs)
	protected.GET("/delivery/execution-tasks/:taskID/artifacts", deps.Delivery.ListExecutionArtifacts)
	protected.POST("/delivery/execution-tasks/:taskID/cancel", deps.Delivery.CancelExecutionTask)
	protected.POST("/delivery/execution-tasks/:taskID/retry", deps.Delivery.RetryExecutionTask)
	protected.GET("/delivery/blueprints", deps.Delivery.ListDeliveryBlueprints)
	protected.POST("/delivery/blueprints", deps.Delivery.CreateDeliveryBlueprint)
	protected.PUT("/delivery/blueprints/:blueprintID", deps.Delivery.UpdateDeliveryBlueprint)
	protected.GET("/delivery/blueprints/:blueprintID/usage", deps.Delivery.GetDeliveryBlueprintUsage)
	protected.POST("/delivery/blueprints/:blueprintID/render-spec", deps.Delivery.RenderDeliveryBlueprintSpec)
	protected.POST("/delivery/blueprints/:blueprintID/bootstrap-application", deps.Delivery.BootstrapApplicationFromBlueprint)
	protected.POST("/delivery/drafts", deps.Delivery.CreateDeliveryDraft)
	protected.GET("/delivery/drafts/:draftID", deps.Delivery.GetDeliveryDraft)
	protected.POST("/delivery/drafts/:draftID/confirm", deps.Delivery.ConfirmDeliveryDraft)
	protected.POST("/delivery/plans", deps.Delivery.CreateDeliveryPlan)
	protected.GET("/delivery/plans/:planID", deps.Delivery.GetDeliveryPlan)
	protected.POST("/delivery/plans/:planID/confirm", deps.Delivery.ConfirmDeliveryPlan)
	protected.POST("/delivery/plans/:planID/approval", deps.Delivery.DecideDeliveryPlanApproval)
}

func registerDeliveryCatalogRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.POST("/application-environments", deps.Catalog.CreateApplicationEnvironment)
	protected.PUT("/application-environments/:applicationEnvironmentID", deps.Catalog.UpdateApplicationEnvironment)
	protected.DELETE("/application-environments/:applicationEnvironmentID", deps.Catalog.DeleteApplicationEnvironment)
	protected.GET("/build-templates", deps.Catalog.ListBuildTemplates)
	protected.GET("/build-templates/:buildTemplateID/usage", deps.Catalog.GetBuildTemplateUsage)
	protected.POST("/build-templates", deps.Catalog.CreateBuildTemplate)
	protected.PUT("/build-templates/:buildTemplateID", deps.Catalog.UpdateBuildTemplate)
	protected.DELETE("/build-templates/:buildTemplateID", deps.Catalog.DeleteBuildTemplate)
	protected.GET("/workflow-templates", deps.Catalog.ListWorkflowTemplates)
	protected.GET("/workflow-templates/:workflowTemplateID/usage", deps.Catalog.GetWorkflowTemplateUsage)
	protected.POST("/workflow-templates", deps.Catalog.CreateWorkflowTemplate)
	protected.PUT("/workflow-templates/:workflowTemplateID", deps.Catalog.UpdateWorkflowTemplate)
	protected.DELETE("/workflow-templates/:workflowTemplateID", deps.Catalog.DeleteWorkflowTemplate)
}

func registerDeliveryApplicationRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/applications", deps.Applications.ListApplications)
	protected.POST("/applications", deps.Applications.CreateApplication)
	protected.GET("/applications/:applicationID", deps.Applications.GetApplication)
	protected.GET("/applications/:applicationID/detail", deps.Delivery.GetApplicationDetail)
	protected.GET("/applications/:applicationID/runtime", deps.Delivery.GetApplicationRuntimeDetail)
	protected.POST("/applications/:applicationID/delivery-actions", deps.Delivery.TriggerApplicationDeliveryAction)
	protected.GET("/applications/:applicationID/application-environments/:applicationEnvironmentID/workloads/:workloadName/runtime", deps.Delivery.GetApplicationWorkloadRuntimeDetail)
	protected.GET("/applications/:applicationID/services", deps.Applications.ListApplicationServices)
	protected.POST("/applications/:applicationID/services", deps.Applications.CreateApplicationService)
	protected.GET("/applications/:applicationID/services/:serviceID", deps.Applications.GetApplicationService)
	protected.PUT("/applications/:applicationID/services/:serviceID", deps.Applications.UpdateApplicationService)
	protected.DELETE("/applications/:applicationID/services/:serviceID", deps.Applications.DeleteApplicationService)
	protected.PUT("/applications/:applicationID", deps.Applications.UpdateApplication)
	protected.DELETE("/applications/:applicationID", deps.Applications.DeleteApplication)
}

func registerDeliveryExecutionRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/builds", deps.Builds.ListBuilds)
	protected.GET("/builds/:buildID", deps.Builds.GetBuild)
	protected.POST("/builds/trigger", deps.Builds.TriggerBuild)
	protected.GET("/workflows", deps.Workflows.List)
	protected.GET("/workflows/:workflowRunID", deps.Workflows.Get)
	protected.POST("/workflows/trigger", deps.Workflows.Trigger)
	protected.POST("/workflows/:workflowRunID/approve", deps.Workflows.Approve)
	protected.POST("/workflows/:workflowRunID/reject", deps.Workflows.Reject)
	protected.GET("/registries", deps.Registries.List)
	protected.POST("/registries", deps.Registries.Create)
	protected.PUT("/registries/:connectionID", deps.Registries.Update)
	protected.DELETE("/registries/:connectionID", deps.Registries.Delete)
	protected.GET("/releases", deps.Releases.ListReleases)
	protected.GET("/releases/:releaseID", deps.Releases.GetRelease)
	protected.POST("/releases/trigger", deps.Releases.TriggerRelease)
	protected.GET("/delivery/release-board", deps.Delivery.ListReleaseBoard)
	protected.GET("/integrations/gitlab/projects", deps.Applications.ListGitRepositories)
	protected.GET("/integrations/gitlab/branches", deps.Applications.ListGitBranches)
	protected.GET("/integrations/gitlab/tags", deps.Applications.ListGitTags)
	protected.GET("/integrations/gitlab/commits", deps.Applications.ListGitCommits)
	protected.GET("/repositories", deps.Applications.ListRepositories)
	protected.POST("/repositories", deps.Applications.CreateRepository)
	protected.GET("/repositories/:repositoryID", deps.Applications.GetRepository)
	protected.PUT("/repositories/:repositoryID", deps.Applications.UpdateRepository)
	protected.DELETE("/repositories/:repositoryID", deps.Applications.DeleteRepository)
}
