package routes

import (
	"github.com/gin-gonic/gin"
	cfgpkg "github.com/opensoha/soha/internal/infrastructure/config"
)

func registerDeliveryRoutes(protected gin.IRoutes, cfg cfgpkg.Config, deps Dependencies) {
	_ = cfg
	registerDeliveryRuntimeRoutes(protected, deps)
	registerDeliveryCatalogRoutes(protected, deps)
	registerDeliveryApplicationRoutes(protected, deps)
	registerDeliveryExecutionRoutes(protected, deps)
	registerDeliveryBatchRoutes(protected, deps)
	registerDeliveryTriggerRoutes(protected, deps)
}

func registerDeliveryRuntimeRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/delivery/manifest-packages", deps.Manifests.List)
	protected.POST("/delivery/manifest-packages", deps.Manifests.Create)
	protected.GET("/delivery/manifest-packages/:manifestPackageID", deps.Manifests.Get)
	protected.PUT("/delivery/manifest-packages/:manifestPackageID", deps.Manifests.Update)
	protected.DELETE("/delivery/manifest-packages/:manifestPackageID", deps.Manifests.Delete)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/publish", deps.Manifests.Publish)
	protected.GET("/delivery/manifest-packages/:manifestPackageID/revisions", deps.Manifests.ListRevisions)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/revisions", deps.Manifests.SaveRevision)
	protected.GET("/delivery/manifest-packages/:manifestPackageID/source", deps.ManifestSources.Get)
	protected.PUT("/delivery/manifest-packages/:manifestPackageID/source", deps.ManifestSources.Update)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/render", deps.ManifestSources.Render)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/preflight", deps.ManifestSources.Preflight)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/sync", deps.ManifestSources.Sync)
	protected.GET("/delivery/manifest-packages/:manifestPackageID/sync-runs", deps.ManifestSources.ListSyncRuns)
	protected.POST("/delivery/manifest-sources/:manifestSourceID/webhook", deps.ManifestSources.SyncWebhook)
	protected.GET("/delivery/manifest-packages/:manifestPackageID/bindings", deps.ManifestBindings.List)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/bindings", deps.ManifestBindings.Create)
	protected.PUT("/delivery/manifest-bindings/:manifestBindingID", deps.ManifestBindings.Update)
	protected.DELETE("/delivery/manifest-bindings/:manifestBindingID", deps.ManifestBindings.Delete)
	protected.POST("/delivery/manifest-bindings/:manifestBindingID/desired-revision", deps.ManifestBindings.SetDesiredRevision)
	protected.GET("/delivery/manifest-deployments", deps.ManifestDeployments.List)
	protected.GET("/delivery/manifest-deployments/:manifestDeploymentID", deps.ManifestDeployments.Get)
	protected.POST("/delivery/manifest-deployments/:manifestDeploymentID/reconcile", deps.ManifestDeployments.Reconcile)
	protected.POST("/delivery/manifest-deployments/:manifestDeploymentID/repair", deps.ManifestDeployments.Repair)
	protected.POST("/delivery/manifest-deployments/:manifestDeploymentID/adopt", deps.ManifestDeployments.Adopt)
	protected.POST("/delivery/manifest-deployments/:manifestDeploymentID/rollback", deps.ManifestDeployments.Rollback)
	protected.GET("/delivery/manifest-packages/:manifestPackageID/delivery-intents", deps.ManifestIntents.List)
	protected.POST("/delivery/manifest-packages/:manifestPackageID/delivery-intents", deps.ManifestIntents.Create)
	protected.POST("/delivery/manifest-delivery-intents/:manifestDeliveryIntentID/accept", deps.ManifestIntents.Accept)
	protected.POST("/delivery/manifest-delivery-intents/:manifestDeliveryIntentID/reject", deps.ManifestIntents.Reject)
	protected.GET("/application-environments", deps.Catalog.ListApplicationEnvironments)
	protected.GET("/application-environments/:applicationEnvironmentID", deps.Catalog.GetApplicationEnvironment)
	protected.GET("/application-environments/:applicationEnvironmentID/detail", deps.Delivery.GetApplicationEnvironmentDetail)
	protected.GET("/application-environments/target-candidates", deps.Delivery.ListTargetCandidates)
	protected.POST("/application-environments/imports", deps.Delivery.ImportKubernetesServices)
	protected.POST("/application-environments/helm-release-imports", deps.Delivery.ImportHelmReleases)
	protected.GET("/delivery/artifacts", deps.Delivery.ListArtifacts)
	protected.GET("/delivery/runtime/builds/:buildID", deps.Delivery.GetBuildRuntimeDetail)
	protected.GET("/delivery/runtime/workflows/:workflowRunID", deps.Delivery.GetWorkflowRuntimeDetail)
	protected.GET("/delivery/runtime/releases/:releaseID", deps.Delivery.GetReleaseRuntimeDetail)
	protected.GET("/delivery/runtime/release-bundles/:bundleID", deps.Delivery.GetReleaseBundleRuntimeDetail)
	protected.GET("/delivery/runtime/execution-tasks/:taskID", deps.Delivery.GetExecutionTaskRuntimeDetail)
	protected.GET("/delivery/release-bundles", deps.Delivery.ListReleaseBundles)
	protected.GET("/delivery/release-bundles/:bundleID", deps.Delivery.GetReleaseBundle)
	protected.GET("/delivery/release-bundles/:bundleID/artifacts", deps.Delivery.ListReleaseBundleArtifacts)
	protected.GET("/delivery/execution-tasks", deps.Delivery.ListExecutionTasks)
	protected.GET("/delivery/execution-tasks/:taskID", deps.Delivery.GetExecutionTask)
	protected.GET("/delivery/execution-tasks/:taskID/rollout", deps.ManifestDeployments.GetTaskRollout)
	protected.POST("/delivery/execution-tasks/:taskID/rollout", deps.ManifestDeployments.ControlTaskRollout)
	protected.GET("/delivery/execution-tasks/:taskID/logs", deps.Delivery.ListExecutionLogs)
	protected.GET("/delivery/execution-tasks/:taskID/artifacts", deps.Delivery.ListExecutionArtifacts)
	protected.POST("/delivery/execution-tasks/:taskID/cancel", deps.Delivery.CancelExecutionTask)
	protected.POST("/delivery/execution-tasks/:taskID/retry", deps.Delivery.RetryExecutionTask)
	protected.GET("/delivery/blueprints", deps.Delivery.ListDeliveryBlueprints)
	protected.POST("/delivery/blueprints", deps.Delivery.CreateDeliveryBlueprint)
	protected.PUT("/delivery/blueprints/:blueprintID", deps.Delivery.UpdateDeliveryBlueprint)
	protected.GET("/delivery/blueprints/:blueprintID/usage", deps.Delivery.GetDeliveryBlueprintUsage)
	protected.POST("/delivery/blueprints/:blueprintID/render-spec", deps.Delivery.RenderDeliveryBlueprintSpec)
	protected.POST("/delivery/blueprints/:blueprintID/bootstrap-application", deps.Delivery.BootstrapApplicationFromBlueprint)
	protected.POST("/delivery/drafts", deps.Delivery.CreateDeliveryDraft)
	protected.GET("/delivery/drafts/:draftID", deps.Delivery.GetDeliveryDraft)
	protected.POST("/delivery/drafts/:draftID/confirm", deps.Delivery.ConfirmDeliveryDraft)
	protected.POST("/delivery/plans", deps.Delivery.CreateDeliveryPlan)
	protected.GET("/delivery/plans/:planID", deps.Delivery.GetDeliveryPlan)
	protected.POST("/delivery/plans/:planID/confirm", deps.Delivery.ConfirmDeliveryPlan)
	protected.POST("/delivery/plans/:planID/approval", deps.Delivery.DecideDeliveryPlanApproval)
}

func registerDeliveryCatalogRoutes(protected gin.IRoutes, deps Dependencies) {
	registerTemplateSourceRoutes(protected, deps)
	protected.POST("/delivery/documents/preview", deps.DeliveryDocuments.Preview)
	protected.POST("/delivery/documents/imports/:previewID/apply", deps.DeliveryDocuments.Apply)
	protected.GET("/delivery/documents/:kind/:objectID/export", deps.DeliveryDocuments.Export)
	protected.GET("/delivery/environments", deps.Catalog.ListEnvironments)
	protected.POST("/application-environments", deps.Catalog.CreateApplicationEnvironment)
	protected.PUT("/application-environments/:applicationEnvironmentID", deps.Catalog.UpdateApplicationEnvironment)
	protected.DELETE("/application-environments/:applicationEnvironmentID", deps.Catalog.DeleteApplicationEnvironment)
	protected.GET("/deployment-templates", deps.DeploymentTemplates.List)
	protected.POST("/deployment-templates", deps.DeploymentTemplates.Save)
	protected.GET("/deployment-templates/:deploymentTemplateID", deps.DeploymentTemplates.Get)
	protected.PUT("/deployment-templates/:deploymentTemplateID", deps.DeploymentTemplates.Save)
	protected.DELETE("/deployment-templates/:deploymentTemplateID", deps.DeploymentTemplates.Deprecate)
	protected.GET("/deployment-templates/:deploymentTemplateID/versions", deps.DeploymentTemplates.Versions)
	protected.GET("/deployment-templates/:deploymentTemplateID/versions/:version", deps.DeploymentTemplates.Version)
	protected.POST("/deployment-templates/:deploymentTemplateID/publish", deps.DeploymentTemplates.Publish)
	protected.POST("/applications/:applicationID/deployment-template-preview", deps.DeploymentTemplates.Preview)
	protected.GET("/build-templates", deps.Catalog.ListBuildTemplates)
	protected.GET("/build-templates/:buildTemplateID/usage", deps.Catalog.GetBuildTemplateUsage)
	protected.POST("/build-templates", deps.Catalog.CreateBuildTemplate)
	protected.PUT("/build-templates/:buildTemplateID", deps.Catalog.UpdateBuildTemplate)
	protected.DELETE("/build-templates/:buildTemplateID", deps.Catalog.DeleteBuildTemplate)
	protected.GET("/workflow-templates", deps.Catalog.ListWorkflowTemplates)
	protected.GET("/delivery/workflow-catalog", deps.Catalog.ListWorkflowCatalog)
	protected.GET("/delivery/execution-history", deps.Workflows.ListExecutionHistory)
	protected.GET("/workflow-templates/:workflowTemplateID/usage", deps.Catalog.GetWorkflowTemplateUsage)
	protected.POST("/workflow-templates", deps.Catalog.CreateWorkflowTemplate)
	protected.PUT("/workflow-templates/:workflowTemplateID", deps.Catalog.UpdateWorkflowTemplate)
	protected.DELETE("/workflow-templates/:workflowTemplateID", deps.Catalog.DeleteWorkflowTemplate)
	protected.GET("/build-templates/:buildTemplateID", deps.TemplateVersions.GetBuildTemplate)
	protected.GET("/build-templates/:buildTemplateID/versions", deps.TemplateVersions.ListBuildTemplateVersions)
	protected.GET("/build-templates/:buildTemplateID/versions/:version", deps.TemplateVersions.GetBuildTemplateVersion)
	protected.POST("/build-templates/:buildTemplateID/publish", deps.TemplateVersions.PublishBuildTemplate)
	protected.GET("/workflow-templates/:workflowTemplateID", deps.TemplateVersions.GetWorkflowTemplate)
	protected.GET("/workflow-templates/:workflowTemplateID/versions", deps.TemplateVersions.ListWorkflowTemplateVersions)
	protected.GET("/workflow-templates/:workflowTemplateID/versions/:version", deps.TemplateVersions.GetWorkflowTemplateVersion)
	protected.POST("/workflow-templates/:workflowTemplateID/publish", deps.TemplateVersions.PublishWorkflowTemplate)
}

func registerTemplateSourceRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/delivery/template-sources", deps.TemplateSources.List)
	protected.POST("/delivery/template-sources", deps.TemplateSources.Save)
	protected.GET("/delivery/template-sources/:sourceID", deps.TemplateSources.Get)
	protected.PUT("/delivery/template-sources/:sourceID", deps.TemplateSources.Save)
	protected.DELETE("/delivery/template-sources/:sourceID", deps.TemplateSources.Remove)
	protected.GET("/delivery/template-sources/:sourceID/objects", deps.TemplateSources.Objects)
	protected.POST("/delivery/template-sources/:sourceID/sync", deps.TemplateSources.Sync)
	protected.GET("/delivery/template-sources/:sourceID/sync-runs", deps.TemplateSources.Runs)
	protected.GET("/delivery/template-sources/:sourceID/sync-runs/:runID", deps.TemplateSources.Run)
	protected.POST("/delivery/template-sources/:sourceID/sync-runs/:runID/apply", deps.TemplateSources.Apply)
	protected.POST("/delivery/template-sources/:sourceID/objects/:kind/:objectID/detach", deps.TemplateSources.Remove)
	protected.GET("/delivery/documents/:kind/:objectID/source", deps.TemplateSources.SourceInfo)
}

func registerDeliveryApplicationRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/applications", deps.Applications.ListApplications)
	protected.POST("/applications", deps.Applications.CreateApplication)
	protected.GET("/applications/:applicationID", deps.Applications.GetApplication)
	protected.POST("/applications/:applicationID/repository-analysis", deps.Applications.AnalyzeRepository)
	protected.POST("/applications/:applicationID/helm-chart", deps.Delivery.InspectApplicationHelmChart)
	protected.GET("/applications/:applicationID/detail", deps.Delivery.GetApplicationDetail)
	protected.GET("/applications/:applicationID/runtime", deps.Delivery.GetApplicationRuntimeDetail)
	protected.PUT("/applications/:applicationID/application-environments/:applicationEnvironmentID/workflow", deps.Catalog.SaveApplicationWorkflow)
	protected.POST("/applications/:applicationID/delivery-actions", deps.Delivery.TriggerApplicationDeliveryAction)
	protected.GET("/applications/:applicationID/application-environments/:applicationEnvironmentID/workloads/:workloadName/runtime", deps.Delivery.GetApplicationWorkloadRuntimeDetail)
	protected.POST("/delivery/applications/:applicationID/environments/:applicationEnvironmentID/logs/query", deps.Delivery.QueryApplicationEnvironmentLogs)
	protected.POST("/delivery/applications/:applicationID/environments/:applicationEnvironmentID/logs/stream-ticket", deps.Delivery.IssueApplicationEnvironmentLogStreamTicket)
	protected.GET("/delivery/applications/:applicationID/environments/:applicationEnvironmentID/logs/stream", deps.Delivery.StreamApplicationEnvironmentLogs)
	protected.GET("/applications/:applicationID/services", deps.Applications.ListApplicationServices)
	protected.POST("/applications/:applicationID/services", deps.Applications.CreateApplicationService)
	protected.GET("/applications/:applicationID/services/:serviceID", deps.Applications.GetApplicationService)
	protected.PUT("/applications/:applicationID/services/:serviceID", deps.Applications.UpdateApplicationService)
	protected.DELETE("/applications/:applicationID/services/:serviceID", deps.Applications.DeleteApplicationService)
	protected.PUT("/applications/:applicationID", deps.Applications.UpdateApplication)
	protected.DELETE("/applications/:applicationID", deps.Applications.DeleteApplication)
}

func registerDeliveryExecutionRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/builds", deps.Builds.ListBuilds)
	protected.GET("/applications/:applicationID/buildpacks-capability", deps.Builds.BuildpacksCapability)
	protected.GET("/builds/:buildID", deps.Builds.GetBuild)
	protected.POST("/builds/trigger", deps.Builds.TriggerBuild)
	protected.GET("/workflows", deps.Workflows.List)
	protected.GET("/workflows/:workflowRunID", deps.Workflows.Get)
	protected.POST("/workflows/trigger", deps.Workflows.Trigger)
	protected.POST("/workflows/:workflowRunID/approve", deps.Workflows.Approve)
	protected.POST("/workflows/:workflowRunID/reject", deps.Workflows.Reject)
	protected.GET("/registries", deps.Registries.List)
	protected.POST("/registries", deps.Registries.Create)
	protected.PUT("/registries/:connectionID", deps.Registries.Update)
	protected.DELETE("/registries/:connectionID", deps.Registries.Delete)
	protected.GET("/releases", deps.Releases.ListReleases)
	protected.GET("/releases/:releaseID", deps.Releases.GetRelease)
	protected.POST("/releases/trigger", deps.Releases.TriggerRelease)
	protected.GET("/delivery/release-board", deps.Delivery.ListReleaseBoard)
	protected.GET("/integrations/gitlab/projects", deps.Applications.ListGitRepositories)
	protected.GET("/integrations/gitlab/branches", deps.Applications.ListGitBranches)
	protected.GET("/integrations/gitlab/tags", deps.Applications.ListGitTags)
	protected.GET("/integrations/gitlab/commits", deps.Applications.ListGitCommits)
	protected.GET("/repositories", deps.Applications.ListRepositories)
	protected.POST("/repositories", deps.Applications.CreateRepository)
	protected.GET("/repositories/:repositoryID", deps.Applications.GetRepository)
	protected.PUT("/repositories/:repositoryID", deps.Applications.UpdateRepository)
	protected.DELETE("/repositories/:repositoryID", deps.Applications.DeleteRepository)
}

func registerDeliveryBatchRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/delivery-workflows", deps.DeliveryBatches.ListWorkflows)
	protected.POST("/delivery-workflows", deps.DeliveryBatches.CreateWorkflow)
	protected.GET("/delivery-workflows/:deliveryWorkflowID", deps.DeliveryBatches.GetWorkflow)
	protected.PUT("/delivery-workflows/:deliveryWorkflowID", deps.DeliveryBatches.UpdateWorkflow)
	protected.GET("/delivery-batches", deps.DeliveryBatches.ListBatches)
	protected.POST("/delivery-batches", deps.DeliveryBatches.CreateBatch)
	protected.GET("/delivery-batches/:deliveryBatchID", deps.DeliveryBatches.GetBatch)
	protected.POST("/delivery-batches/:deliveryBatchID/cancel", deps.DeliveryBatches.CancelBatch)
}

func registerDeliveryTriggerRoutes(protected gin.IRoutes, deps Dependencies) {
	protected.GET("/delivery/triggers", deps.DeliveryTriggers.List)
	protected.POST("/delivery/triggers", deps.DeliveryTriggers.Save)
	protected.GET("/delivery/triggers/:triggerID", deps.DeliveryTriggers.Get)
	protected.PUT("/delivery/triggers/:triggerID", deps.DeliveryTriggers.Save)
	protected.GET("/delivery/triggers/:triggerID/events", deps.DeliveryTriggers.Events)
}
